name: Score Android Release

on:
  workflow_dispatch
  
jobs:
  build:
    name: Build & Upload AAB
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'  # or your current Flutter version

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Flutter pub get
      run: flutter pub get

    - name: Decode Keystore & Create Properties
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        KEYSTORE_PATH_ON_RUNNER: /home/runner/upload-keystore.jks
      run: |
        echo "Decoding Keystore to $KEYSTORE_PATH_ON_RUNNER ..."
        echo $KEYSTORE_BASE64 | base64 --decode > $KEYSTORE_PATH_ON_RUNNER
        
        echo "Creating key.properties..."
        printf "%s\n" \
          "storePassword=$STORE_PASSWORD" \
          "keyPassword=$KEY_PASSWORD" \
          "keyAlias=$KEY_ALIAS" \
          "storeFile=$KEYSTORE_PATH_ON_RUNNER" > android/key.properties # Use absolute path
          
        echo "Files created successfully."
        
    # Calculate the commit count as the build number
    - name: Set Build Number
      id: build_number # Give this step an ID to reference its output
      run: echo "COUNT=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT

    - name: Build release AAB
      run: flutter build appbundle --release --build-number=${{ steps.build_number.outputs.COUNT }} # Use the calculated count

    - name: Upload Release AAB Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-aab # Name of the artifact zip file
        path: build/app/outputs/bundle/release/*.aab # Path to the AAB file(s)
