name: Score Android Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build & Upload AAB
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'  # or your current Flutter version

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Flutter pub get
      run: flutter pub get

    - name: Decode keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/upload-keystore.jks
    
    - name: DEBUG: Print env var lengths
      run: |
        echo "KEYSTORE_PASSWORD length: ${#KEYSTORE_PASSWORD}"
        echo "KEY_PASSWORD length: ${#KEY_PASSWORD}"
        echo "KEY_ALIAS length: ${#KEY_ALIAS}"
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

    - name: Build release AAB
      run: flutter build appbundle --release

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/app/outputs/bundle/release/app-release.aab
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
